### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [nakata59/comic_gold_rush#11]
@nakata59 
MVPリリースお疲れ様でした:tada:

下記の観点でレビューしております。
1. 就活において十分な技術力を示せる機能を実装しているか
2. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## 就活において十分な技術力を示せる機能を実装しているか
APIを投げて独自のロジックを使って情報の精査している部分はいいですね。
ただitems_controllerがfat controllerになっているので、APIでのsearch周りの処理をserviceクラスに切り出すなど、下記の記事を参考にこの部分をリファクタしてあげるといいかなと思います！
https://techracho.bpsinc.jp/hachi8833/2021_10_05/112108

またがっつりRailsのメリットを用いている機能があまりないので、その辺りを使って機能を修正、追加機能の実装をするといいかなと思います。
このアプリをベースに考えると下記の機能が一目置かれる技術の実装としていいかなと思います！
- Hotwire
- ActionCable
- フォームのオートコンプリート
- お気に入りからの自動レコメンド

rubocopで静的コードチェックをしておいてください。
コードの見た目が整っていない箇所が多々あるので、レビュー時にみやすいようなコードにしておきましょう！

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
下記の部分が気になったので本リリースまでに修正しておきましょう。
- スクロールしないと最後まで見れないので、widthによって横にも表示するようにしましょう
- 検索時に時間がかかってしまうので、パフォーマンスを上げる or UIで検索している画面を表示する
- 検索は１つの画面でさまざまな検索ができるようにする（出版社、キーワードなどひとまとめにしてあげる）
- 新規登録、ログイン、検索などのフォームは中央に配置して、それぞれ見た目をよくする
- データ検索したあと、フォームに検索情報が消えるので残しておく

READMEに記載している課題解決の機能は果たせているので、上記のフィードバック内容を進めていただき、エンジニアとしての技術の見せ方やサービスとしての見せ方を追加・修正できれば、就活フェーズに入って大丈夫です。

こちらの内容を確認いただき、それぞれissueでタスクを作成できたらcloseしてもらって構いません。
以上よろしくお願いします。

**Comment by nakata59** [comment]
@kerochelo 
お疲れ様です。
リアクション遅くなり誠に申し訳ございません。
忙しい中、レビューいただきありがとうございました
いただいたアドバイスから下記issueを作成しました。

#15 ユーザー検索画面オートコンプリート化
#16　検索中のインジケーター追加
#17 UIの横幅に余白を持たせる
#18 ブックマーク機能にhotwire適応
#19 「探す」&「キーワードから探す」のviewを統合
#20 お気に入りからの自動レコメンド

issueを作成しましたのでこちらのissueはcloseさせていただきます。
